### ISSUE TITLE
More libraries need to be installed on ubuntu

### ISSUE THREAD

**Issue by daudazimkhan** [membraneframework/guide#4]
I think the following libraries also need to be documented (for Ubuntu):

- libswresample-dev
- libavutil-dev

Otherwise, compilation fails

**Comment by bblaszkow06** [comment]
Thanks for catching that! Will fix it right away :wink:

**Comment by bblaszkow06** [comment]
Fixed in https://github.com/membraneframework/guide/commit/82434593b5bee24004ea8e2a96c33f3791ef1e5d
